"""Utility helpers for AGraph expressions.

Run a small usage example with::

    python -m bingo.expressions.agraph.utils
"""

import numpy as np

from .pyagraph import CONSTANT, INTEGER, TERMINAL_IDS


def _draw_padding_expression(generator, minimum_size):
    if generator.max_size < minimum_size:
        raise ValueError(
            "generator.max_size must be at least the base expression size "
            f"({minimum_size})"
        )

    while True:
        random_individual = generator()
        random_expression = random_individual.expression
        if random_expression.raw_command_array.shape[0] >= minimum_size:
            return random_expression


def _build_interspersed_base_positions(total_size, base_size, rng):
    if base_size > total_size:
        raise ValueError("base_size cannot exceed total_size")

    if base_size == 0:
        return np.empty(0, dtype=int)

    if base_size == 1:
        return np.array([total_size - 1], dtype=int)

    n_padding = total_size - base_size
    interior_base_size = base_size - 1
    interior_total_size = total_size - 1
    if n_padding == 0:
        positions = np.arange(total_size, dtype=int)
        positions[-1] = total_size - 1
        return positions

    gap_counts = np.zeros(interior_base_size, dtype=int)

    if n_padding == 1 or interior_base_size == 1:
        gap_counts[int(rng.integers(interior_base_size))] += n_padding
    else:
        seeded_gaps = rng.choice(interior_base_size, size=2, replace=False)
        gap_counts[seeded_gaps] += 1
        remaining = n_padding - 2
        if remaining:
            gap_counts += rng.multinomial(
                remaining, np.full(interior_base_size, 1.0 / interior_base_size)
            )

    positions = np.empty(base_size, dtype=int)
    cursor = 0
    for i, gap_count in enumerate(gap_counts):
        cursor += int(gap_count)
        positions[i] = cursor
        cursor += 1
    positions[-1] = interior_total_size
    return positions


def _write_remapped_rows(
    target,
    source_commands,
    row_mapping,
    constant_offset,
    integer_offset,
):
    for old_row, new_row in enumerate(row_mapping):
        row = source_commands[old_row].copy()
        op = int(row[0])

        if op == CONSTANT:
            row[1] = row[2] = int(row[1]) + constant_offset
        elif op == INTEGER:
            row[1] = row[2] = int(row[1]) + integer_offset
        elif op not in TERMINAL_IDS:
            row[1] = row_mapping[int(row[1])]
            row[2] = row_mapping[int(row[2])]

        target[new_row] = row


def pad_agraph_expression(base_expression, generator):
    """Pad an AGraphExpression with inactive rows from a random expression.

    The returned expression has the same simplified behavior as
    ``base_expression``, but its raw command array includes additional dead
    rows copied from a random expression generated by ``generator``.

    Parameters
    ----------
    base_expression : AGraphExpression
        Python or C++ AGraphExpression to pad.
    generator : AGraphGenerator
        Generator used to draw the random padding expression.

    Returns
    -------
    AGraphExpression
        A padded expression of the same backend type as ``base_expression``.
    """

    base_commands = np.asarray(base_expression.raw_command_array, dtype=np.uint8)
    if base_commands.shape[0] == 0:
        return base_expression.copy()

    padding_expression = _draw_padding_expression(generator, base_commands.shape[0])
    padding_commands = np.asarray(padding_expression.raw_command_array, dtype=np.uint8)

    total_size = padding_commands.shape[0]
    base_size = base_commands.shape[0]
    base_positions = _build_interspersed_base_positions(total_size, base_size, generator._rng)
    padding_positions = np.setdiff1d(
        np.arange(total_size, dtype=int), base_positions, assume_unique=True
    )

    raw_constants = tuple(padding_expression.raw_constants) + tuple(
        base_expression.raw_constants
    )
    raw_integers = tuple(padding_expression.raw_integers) + tuple(
        base_expression.raw_integers
    )

    max_uint8 = np.iinfo(np.uint8).max
    if len(raw_constants) > max_uint8 + 1:
        raise ValueError("combined raw_constants exceed uint8 indexing capacity")
    if len(raw_integers) > max_uint8 + 1:
        raise ValueError("combined raw_integers exceed uint8 indexing capacity")

    padded_commands = np.empty((total_size, 3), dtype=np.uint8)
    _write_remapped_rows(
        padded_commands,
        padding_commands,
        padding_positions,
        constant_offset=0,
        integer_offset=0,
    )
    _write_remapped_rows(
        padded_commands,
        base_commands,
        base_positions,
        constant_offset=len(padding_expression.raw_constants),
        integer_offset=len(padding_expression.raw_integers),
    )

    simplification = getattr(
        base_expression,
        "_simplification",
        getattr(padding_expression, "_simplification", "cas"),
    )
    propagate_constants = getattr(base_expression, "propagate_constants", False)
    padded_expression = type(base_expression)(
        simplification=simplification,
        propagate_constants=propagate_constants,
    )
    padded_expression.raw_command_array = padded_commands
    padded_expression.raw_constants = raw_constants
    padded_expression.raw_integers = raw_integers

    # Preserve the current evaluation-facing constant values even when the base
    # expression has fitted constants that were not propagated back to raw.
    padded_expression.constants = base_expression.constants
    if hasattr(padded_expression, "_is_fitted"):
        padded_expression._is_fitted = base_expression.__sklearn_is_fitted__()

    return padded_expression


__all__ = ["pad_agraph_expression"]


def _format_raw_stack(expr):
    rows = []
    utilized = list(expr.get_utilized_commands())
    for i, row in enumerate(expr.raw_command_array):
        marker = "U" if utilized[i] else " "
        rows.append(
            f"[{i:02d}] {marker} op={int(row[0]):2d} p1={int(row[1]):2d} p2={int(row[2]):2d}"
        )
    return "\n".join(rows)


def _demo():
    from .component_generator import ComponentGenerator
    from .generator import AGraphGenerator
    from .pyagraph.expression import AGraphExpression
    from .pyagraph.operators import ADDITION, MULTIPLICATION, SIN, VARIABLE, CONSTANT

    component_gen = ComponentGenerator(input_x_dimension=2, random_state=1)
    for operator in (ADDITION, MULTIPLICATION, SIN):
        component_gen.add_operator(operator)

    generator = AGraphGenerator(
        min_size=7,
        max_size=7,
        component_generator=component_gen,
        simplification="reduce",
        random_state=4,
    )

    base_expression = AGraphExpression(simplification="reduce")
    base_expression.raw_command_array = np.array(
        [
            [VARIABLE, 0, 0],
            [CONSTANT, 0, 0],
            [ADDITION, 0, 1],
        ],
        dtype=np.uint8,
    )
    base_expression.raw_constants = (2.5,)

    padded_expression = pad_agraph_expression(base_expression, generator)

    print("Base expression")
    print(f"  simplified: {base_expression}")
    print(f"  raw_constants: {base_expression.raw_constants}")
    print(_format_raw_stack(base_expression))
    print()

    print("Padded expression")
    print(f"  simplified: {padded_expression}")
    print(f"  raw_constants: {padded_expression.raw_constants}")
    print(_format_raw_stack(padded_expression))
    print()

    print("Checks")
    print(f"  simplified expressions match: {str(base_expression) == str(padded_expression)}")
    print(
        "  raw stack grew: "
        f"{base_expression.raw_command_array.shape[0]} -> {padded_expression.raw_command_array.shape[0]}"
    )


if __name__ == "__main__":
    _demo()
