name: docker
on:
  push:
    branches: [ "master" ]
jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'bingo/'
          submodules: 'recursive'
      - name: Docker login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v2.8.0
        with:
          push: true
          tags: mrbuche/bingo:latest
      - name: Delay before pull
        run: sleep 234s
  test-latest:
    needs: build-latest
    runs-on: ubuntu-latest
    container: mrbuche/bingo
    steps:
      - name: Docker pull and test
        run: |
          python -c 'import bingo; import bingocpp'
          cd /opt/bingo/bingocpp/build/ && make gtest
          cd /opt/bingo/ && pytest tests
