# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Examples

on:
  pull_request:
    paths:
      - "examples/**"
      - "bingo/**"
      - "pyproject.toml"
      - "setup.py"
      - "MANIFEST.in"
      - "requirements.txt"
      - ".github/**"
  push:
    branches: [main, develop]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ./.github/actions/setup-bingo
      with:
        python-version: "3.13"
        dependencies: ".[MPI,ONNX]"
    - name: Install example dependencies
      run: python -m pip install jupyter nbconvert matplotlib
    - name: Run examples
      run: |
        examples/.test_examples.sh
