# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Performance Benchmarks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install MPI
      uses: mpi4py/setup-mpi@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set pythonpath
      run: |
        echo "PYTHONPATH=`pwd`" >> $GITHUB_ENV
    - name: Build bingocpp
      run: |
        ./.build_bingocpp.sh
    - name: Evaluation Benchmark
      run: |
        python tests/performance_benchmarking/performance_benchmarks.py
    - name: Evolution Benchmark
      run: |
        python tests/performance_benchmarking/island_benchmarks.py
