"""Multiple Floats for genetic information

This file contains the several classes that are used for chromosomes
that contains a list of floats for their genetic information.
"""
from .multiple_values import MultipleValueChromosome, \
                            MultipleValueChromosomeGenerator


class MultipleFloatChromosome(MultipleValueChromosome):
    """Multiple float-value individual

    Parameters
    ----------
    values : list of floats
        The genetic information stored in an individual chromosome.
    """
class MultipleFloatChromosomeGenerator(MultipleValueChromosomeGenerator):
    """Generation of a population of Multi-Value chromosomes

    Parameters
    ----------
    random_value_function : user defined function
        A function that returns a randomly generated float value.
    values_per_chromosome : int
        The number of values that each chromosome will hold
    """
    def __call__(self):
        """Generation of a population of size `population_size`
        of Multi-Value chromosomes with lists that contain
        `values_per_list` values.

        Returns
        -------
        list of chromosomes :
            The chromosomes which their values are generated by
            `random_value_function` with the optimization list
            generated by `random_value_function`.
        """
        random_list = self._generate_list(self._values_per_chromosome)
        return MultipleFloatChromosome(random_list)
